version: '3.9'

services:
  web:
    build: ./src/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./src/web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    expose:
      - "5432"
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    working_dir: /var/lib/postgresql/backups
    volumes:
      - ./docker-workdir/postgres/backups/:${PG_BACKUPS:-/var/lib/postgresql/backups/}
      - ./docker-workdir/postgres/data/:${PGDATA:-/var/lib/postgresql/data/}

volumes:
  postgres_data: